# Generated by Django 5.2 on 2025-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100)),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('ph', models.FloatField()),
                ('organic_carbon', models.FloatField()),
                ('soil_rating', models.FloatField()),
                ('weather_condition', models.CharField(max_length=50)),
                ('weather_score', models.FloatField()),
                ('regional_score', models.FloatField()),
                ('farm_size', models.FloatField()),
                ('farm_score', models.FloatField()),
                ('final_score', models.FloatField()),
            ],
        ),
    ]
