# Generated by Django 6.0 on 2025-12-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscoreresult',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditscoreresult',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
